## Numpy

**NumPy Introduction**

NumPy stands for Numerical Python.

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

Installation of NumPy

If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

C:\Users\Your Name>pip install numpy

Import NumPy:

Once NumPy is installed, import it in your applications by adding the import keyword:

In [11]:
# pip install numpy
import numpy as np
np.__version__

'2.3.4'

**NumPy Creating Arrays**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [12]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Dimensions in Arrays**

A dimension in arrays is one level of array depth

In [13]:
# Numpy array dimensions
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr0 = np.array(10)
# Making numpy array with a list makes 1-d arrays
arr1 = np.array([1,2,3,4,5,6])
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix
# arr2 = np.array([[1,2,3,4,5],[6,7,8,9],[10]])
# An array can have any number of dimensions.
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arr3 = np.array(3, ndmin=10)
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
arr3.ndim

10

**Access Array Elements**

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [14]:
#Get the second element from the following array.

arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [15]:
#Access 2-D Arrays
#To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
#Access the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0, 1])
# print('2nd element on 1st row: ', arr[0][1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [23]:
a = np.array([[1,2,2],[3,4,2],[3,5,6]])
a.ndim
a.shape

(3, 3)

In [28]:
#Access the third element of the second array of the first array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


print(arr.shape)
print(arr)
print(arr[0, 1, 2])
#print(arr[0][1][2])

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


**NumPy Array Slicing**

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])


[2 4]


In [31]:
#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


**NumPy Array Shape/reshape**

The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [32]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
# Shape of numpy array
arr1.shape

[1 2 3 4 5 6]


(6,)

In [33]:
#Reshaping arrays
#By reshaping we can add or remove dimensions or change number of elements in each dimension.
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**NumPy Array Iterating**

We can do this using basic for loop of python.

The function nditer() is a helping function that can be used from very basic to very advanced iterations.

In [35]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [36]:
#Iterating over numpy array
for x in np.nditer(arr):
    print(x)

1
2
3


In [37]:
for indx,x in np.ndenumerate(arr):
    print(indx,x)

(0,) 1
(1,) 2
(2,) 3


**NumPy Joining Array**

Joining means putting contents of two or more arrays in a single array.

In [38]:
#Joining multiple array
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,6])
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6])

In [39]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6])

In [40]:
np.vstack((a1,a2))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 6]])

**Splitting NumPy Arrays**

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [41]:
#Spliting Array
#Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6,7])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [42]:
np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]

In [43]:
# An alternate solution is using hsplit() opposite of hstack()
np.hsplit(arr,2)

ValueError: array split does not result in an equal division

**Searching Arrays**

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [45]:
#array elements searching and retun the index of the matched condition
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [46]:
#Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [47]:
#Array Sorting
unsort = np.array([2,4,1,5,7,32,2,0])
np.sort(unsort)

array([ 0,  1,  2,  2,  4,  5,  7, 32])

In [48]:
#Searchsorted return index of specified value to maintain sorted array
np.searchsorted([1,2,4,5,6], 7)

np.int64(5)

**Random Numbers in NumPy**

Random means something that can not be predicted logically.

NumPy offers the random module to work with random numbers.

In [50]:
#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)
#x = np.random.randint(100)
print(x)

31


In [67]:
#return a random integer between 0 and 10
np.random.randint(10)

7

In [52]:
#return array of 5 integer between 0 and 10
#Add a size parameter to specify the shape of the array.
np.random.randint(10, size=(5))

array([9, 0, 7, 0, 2], dtype=int32)

In [53]:
#2*3 array of integer between 0 and 10
np.random.randint(10, size=(3,15))

array([[1, 5, 7, 6, 1, 3, 4, 0, 5, 5, 7, 5, 9, 9, 6],
       [8, 7, 4, 8, 4, 5, 6, 3, 9, 4, 4, 7, 4, 2, 0],
       [6, 2, 3, 1, 7, 2, 9, 7, 2, 5, 3, 9, 4, 0, 8]], dtype=int32)

Generate Random Float

The random module's rand() method returns a random float between 0 and 1.

In [54]:
#return a float num between 0 and 1
np.random.rand()

0.11999109773749905

In [55]:
#return an array of 5 float num between 0 and 1
np.random.rand(5)

array([0.12432329, 0.85970885, 0.2786018 , 0.24540998, 0.3591114 ])

In [56]:
np.random.rand(2,10) #2*3 array of float num between 0 and 1

array([[0.26931409, 0.43803049, 0.34794654, 0.00135052, 0.79889927,
        0.61550183, 0.32382149, 0.20551723, 0.21249736, 0.57379812],
       [0.66960905, 0.03378253, 0.28925854, 0.60797834, 0.40915977,
        0.4314058 , 0.05590846, 0.15502488, 0.69854649, 0.71515824]])

Generate Random Number From Array

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [75]:
#return a random number from the given array
np.random.choice([1,2,3,4,5])

np.int64(5)

In [77]:
#random array of 10 num from the given list
#Add a size parameter to specify the shape of the array.
np.random.choice([1,2,3,4,5], size=(10))

array([2, 3, 3, 1, 3, 5, 2, 4, 4, 3])

In [79]:
#2*3 random array from the given list
np.random.choice([1,2,3,4,5], size=(2,3))

array([[5, 4, 1],
       [3, 3, 4]])

In [81]:
np.random.choice([1,2,3,4,5], p=[0.1,0.2,0.5,0.0,0.2], size=(10))

array([3, 5, 3, 3, 1, 5, 2, 5, 2, 3])

**Some Common Methods**

In [82]:
arr1

array([1, 2, 3, 4, 5, 6])

In [83]:
#return min/max in array
arr1.max()
#arr1.min()

np.int64(6)

In [84]:
#return index of max in array
#arr1.argmax()
arr1.argmin()

np.int64(0)

In [85]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [86]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
#return a sequence
np.arange(0,10,3)

array([0, 3, 6, 9])

In [88]:
arr3 = np.linspace(0, 1, 10)
arr3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**NumPy ufuncs**

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [91]:
# Without ufunc, we can use Python's built-in zip() method:

x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[np.int64(5), np.int64(7), np.int64(9), np.int64(11)]


In [92]:
#With ufunc, we can use the add() function:
z = np.add(x, y)
print(z)

[ 5  7  9 11]


In [93]:
#universal Function
#Simple Arithmatics
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,11,12,13,14])
print('Add: ', np.add(arr1,arr2) )
print('Sub: ', np.subtract(arr1,arr2) )
print('Mul: ', np.multiply(arr1,arr2) )
print('Div: ', np.divide(arr1,arr2) )
print('Mod: ', np.mod(arr1,arr2) )
print('Reminder: ', np.remainder(arr1,arr2) )
print('Power: ', np.power(arr1,arr2) )
print('Absolute: ', np.absolute([-1,2-4,6,0,-7]))


Add:  [11 13 15 17 19]
Sub:  [-9 -9 -9 -9 -9]
Mul:  [10 22 36 52 70]
Div:  [0.1        0.18181818 0.25       0.30769231 0.35714286]
Mod:  [1 2 3 4 5]
Reminder:  [1 2 3 4 5]
Power:  [         1       2048     531441   67108864 6103515625]
Absolute:  [1 2 6 0 7]


In [94]:
#Rounding Decimal
print( np.trunc([-3.22, 4.55]) )
print( np.fix([-2.99, 8.55]) )
print( np.around(8.345, 1) )
print( np.floor([-3.22, 6.44]) )
print( np.ceil([-3.22, 6.44]) )

[-3.  4.]
[-2.  8.]
8.3
[-4.  6.]
[-3.  7.]


In [95]:
# NumPy Logs
arr1 = [1, 2, 3, 4, 5]
print( np.log2(arr1) )
print( np.log10(arr1) )
print( np.log(arr1) )  #Natural Log of base e

[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [104]:
# Example: Guess the number game
# import random module from numpy
import numpy as np

def guess_the_number():
    number = np.random.randint(1, 10)
    tries = 0
    print(number)

    while True:
        guess = int(input("Enter your guess (1-10): "))
        tries += 1

        if guess < number:
            print("Lower number guessed, try again!")
        elif guess > number:
            print("Higher number guessed, try again!")
        else:
            print(f"Congratulations, you guessed the number in {tries} tries!")
            break

guess_the_number()

4
Congratulations, you guessed the number in 1 tries!


**Char Array**

In [96]:
# Char array
np.char.upper(['ali','shahid'])

array(['ALI', 'SHAHID'], dtype='<U6')

In [97]:
np.char.title('this is title:')

array('This Is Title:', dtype='<U14')

In [98]:
np.char.capitalize(['one','two','three'])

array(['One', 'Two', 'Three'], dtype='<U5')

In [99]:
np.char.split('My name is Python')

array(list(['My', 'name', 'is', 'Python']), dtype=object)